# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

elli = User.create(full_name: "Elli Shim", birthdate: '12/12/1990', password:"123")
jon = User.create(full_name: "Jon Wu", birthdate: '23/7/1987', password:"123")
greg = User.create(full_name: "Greg Driza", birthdate: "22/10/1994", password:"123")
rochel = User.create(full_name: "Rochel Levi", birthdate: '27/2/1996', password:"123")
dan = User.create(full_name: "Dan O'Dea", birthdate: '18/6/1979', password:"123")
brendan = User.create(full_name: "Brendan McIlhenny", birthdate: '2/6/1993', password:"123")
erica = User.create(full_name: "Erica Li", birthdate: '4/4/1992', password:"123")
george = User.create(full_name: "George Gore", birthdate: '13/6/1993', password:"123")
josh = User.create(full_name: "Josh Wasserman", birthdate: '24/1/1995', password:"123")
paul = User.create(full_name: "Paul Kristapovich", birthdate: '9/3/1988', password:"123")
yuliya = User.create(full_name: "Yuliya Yasenetska", birthdate: '10/9/1992', password:"123")
priyam = User.create(full_name: "Priyam Sarma", birthdate: '1/1/1989', password:"123")
chris = User.create(full_name: "Chris Johnson", birthdate: '24/3/1999', password:"123")
jake = User.create(full_name: "Jake MacNaughton", birthdate: '23/4/1988', password:"123")
seth = User.create(full_name: "Seth Barden", birthdate: '18/10/1986', password:"123")
joshS = User.create(full_name: "Josh Stillman", birthdate: '9/12/1983', password:"123")
kat = User.create(full_name: "Katerina Papacostas", birthdate: '22/3/1988', password:"123")
tashawn = User.create(full_name: "Tashawn Williams", birthdate: '31/3/1990', password:"123")
erick = User.create(full_name: "Erick Camacho", birthdate: '14/3/1995', password:"123")
connie = User.create(full_name: "Connie Wang", birthdate: '7/10/1994', password:"123")
silvia = User.create(full_name: "Silvia Chung", birthdate: '6/10/1994', password:"123")


# Western Horoscope
aries = Western.create(sign: 'aries', element: 'fire', quality: 'cardinal', planet: 'Mars', img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Aries.svg', description: 'Aries rules the head and leads with the head, often literally walking head first, leaning forwards for speed and focus. Its representatives are naturally brave and rarely afraid of trial and risk. They possess youthful strength and energy, regardless of their age and quickly perform any given tasks.', horoscope: 'Welcome to a brand-new year, Aries! January swooshes in with some epic planetary activity, making sure we all sit up straight and fly right. For starters, the month is bookended by TWO full moons (normally there`s only one per month). Both lunations are supermoons, and one is a change-making eclipse. Yeah, it`s gonna be obvious pretty quickly that 2018 means business. ("We`re not doing 2017 again, guys—is that clear?" declares the cosmos.)')
taurus = Western.create(sign: 'taurus', element: 'earth', quality: 'fixed', planet: 'Venus', img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Taurus.svg', description: 'Practical and well-grounded, Taurus is the sign that harvests the fruits of labor. They feel the need to always be surrounded by love and beauty, turned to the material world, hedonism, and physical pleasures. People born with their Sun in Taurus are sensual and tactile, considering touch and taste the most important of all senses. Stable and conservative, this is one of the most reliable signs of the zodiac, ready to endure and stick to their choices until they reach the point of personal satisfaction.', horoscope: 'Talk about making an entrance! The new year charges in with a flurry of big ideas, vibrant people and exciting conversations. There`ll be no gently easing into 2018 for you, Bull. With the Sun in Capricorn and your visionary ninth house until January 19, you`ll have your sights set on adventurous new possibilities and a few calculated risks.')
gemini = Western.create(sign: 'gemini', element: 'air', quality: 'mutable', planet: 'Mercury', img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Gemini.svg', description: 'Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face. They are sociable, communicative and ready for fun, with a tendency to suddenly get serious, thoughtful and restless. They are fascinated with the world itself, extremely curious, with a constant feeling that there is not enough time to experience everything they want to see.', horoscope: 'Slide into your most sensible footwear as you lunge into 2018, Gemini. You`ll want to land on well-tractioned soles that you can plant on terra firma—and maybe even dig in your heels and claim your turf. This January is bookended by two rare full supermoons, embroidering the month with some rapid-fire moments during which it feels like everything is happening at once. Even master juggler Geminis could get a little overwhelmed by this pace.')
cancer = Western.create(sign: 'cancer', element: 'water', quality: 'cardinal', planet: 'Moon', img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Cancer.svg', description: "Deeply intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know. They are very emotional and sensitive, and care deeply about matters of the family and their home. Cancer is sympathetic and attached to people they keep close. Those born with their Sun in Cancer are very loyal and able to empathize with other people's pain and suffering.", horoscope:'Front and center! The year begins with a January 1 full supermoon in your sign—the first of a rare pair of full moons bookending the month. You`re catapulted into action as soon as 2018 begins, as la luna shines her spotlight on YOUR personal dreams and desires. Declare those to the universe or a few of your closest connections and record them somewhere you won`t forget. This will be a moment of eye-opening clarity that doesn`t come around every day.')
leo = Western.create(sign: 'leo', element: 'fire', quality: 'fixed', planet: 'Sun', img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Leo.svg', description: "People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to. There is a specific strength to a Leo and their 'king of the jungle' status. Leo often has many friends for they are generous and loyal. Self-confident and attractive, this is a Sun sign capable of uniting different groups of people and leading them as one towards a shared cause, and their healthy sense of humor makes collaboration with other people even easier.", horoscope: 'January comes in like a lamb and goes out like a lion—literally! The month is bookended by two full supermoons, the latter being a total lunar eclipse in YOUR sign. The whole world will experience a powerful start to 2018 because of this cosmic activity. But you may have some unfinished business to clear away during the first couple days of the year.')
virgo = Western.create(sign: 'virgo', element: 'earth', quality: 'mutable', planet: 'Mercury', img_url: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Virgo.svg', description: 'Virgos are always paying attention to the smallest details and their deep sense of humanity makes them one of the most careful signs of the zodiac. Their methodical approach to life ensures that nothing is left to chance, and although they are often tender, their heart might be closed for the outer world. This is a sign often misunderstood, not because they lack the ability to express, but because they won’t accept their feelings as valid, true, or even relevant when opposed to reason. The symbolism behind the name speaks well of their nature, born with a feeling they are experiencing everything for the first time.', horoscope: 'Look around, Virgo: Who are the people in your tribe as 2018 begins? The New Year kicks off with a January 1 Cancer full supermoon, which will spotlight your most important friendships and collaborations—as well as areas that need attention, change or closure.')
libra = Western.create(sign: 'libra', element: 'air', quality: 'cardinal', planet: 'Venus', img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Libra.svg', description: 'People born under the sign of Libra are peaceful, fair, and they hate being alone. Partnership is very important for them, as their mirror and someone giving them the ability to be the mirror themselves. These individuals are fascinated by balance and symmetry, they are in a constant chase for justice and equality, realizing through life that the only thing that should be truly important to themselves in their own inner core of personality.', horoscope: 'Ready, set, #goals! January gusts in with a blast of ambition, right from the get-go. The year begins with a January 1 full supermoon—the first of two full moons bookending this month. Because it`s in Cancer, this lunar lift will cast its incandescent beams in your tenth house of career, goals and recognition. The energy can position you for a public role or a leadership position as the calendar turns. Your relationship with an important man, possibly your dad, could be a focal point of this emotional full moon.')
scorpio = Western.create(sign: 'scorpio', element: 'water', quality: 'fixed', planet: 'Mars', img_url: 'https://en.wikipedia.org/wiki/Western_astrology#/media/File:Scorpio.svg', description: 'Scorpio-born are passionate and assertive people. They are determined and decisive, and will research until they find out the truth. Scorpio is a great leader, always aware of the situation and also features prominently in resourcefulness. Scorpio is a Water sign and lives to experience and express emotions. Although emotions are very important for Scorpio, they manifest them differently than other water signs. In any case, you can be sure that the Scorpio will keep your secrets, whatever they may be.', horoscope: "There's no going quietly into 2018 for you, Scorpio. For starters, this will be one of the most boldfaced years you've had in more than a decade, since effusive, auspicious Jupiter is in your sign until November 8—a cosmic boost you only get once every 12 years. On top of that, energizer Mars is in Scorpio until January 26, and when these two fire starters unite on January 6 (their first hookup in your sign since 2006), be prepared to launch! Whatever you've been deliberating over could rapidly transpire.")
sagittarius = Western.create(sign: 'sagittarius', element: 'fire', quality: 'mutable', planet: 'Jupiter', img_url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Sagittarius.svg', description: 'Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs. Their open mind and philosophical view motivates them to wander around the world in search of the meaning of life. Sagittarius is extrovert, optimistic and enthusiastic, and likes changes. Sagittarius-born are able to transform their thoughts into concrete actions and they will do anything to achieve their goals.', horoscope: 'Work hard, rest hard. Your new year gets off to a mostly productive start, as the Sun makes its annual trek through Capricorn and your industrious second house until January 19. You`re eager to roll up the sleeves of your Fair Isle sweater and make headway on those 2018 projects. But not so fast! Energy planet Mars is puttering along on a low tank as it snoozes in Scorpio and your twelfth house of R+R until January 26 (accompanied by your ruler, Jupiter, which is in Scorpio until November).')
capricorn = Western.create(sign: 'capricorn', element: 'earth', quality: 'cardinal', planet: 'Saturn', img_url: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Capricorn.svg', description: 'Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature. These individuals possess an inner state of independence that enables significant progress both in their personal and professional lives. They are masters of self-control and have the ability to lead the way, make solid and realistic plans, and manage many people who work for them at any time. They will learn from their mistakes and get to the top based solely on their experience and expertise.', horoscope: 'And you`re off! The new year begins on a vibrant and extroverted note for you, Capricorn. The Sun is in your sign until January 19, prodding you to take chances and make a start fresh. Meanwhile, energizer Mars is in Scorpio and your eleventh house of group activity, ramping up your social life until January 26. Solo endeavors AND team projects are both cosmically catalyzed.')
aquarius = Western.create(sign: 'aquarius', element: 'air', quality: 'fixed', planet: 'Saturn', img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Aquarius.svg', description: 'Aquarius is an air sign, and as such, uses his mind at every opportunity. If there is no mental stimulation, they are bored and lack a motivation to achieve the best result.', horoscope:'Work hard, rest hard. You`ll need to consciously regulate your energy as 2018 begins, Aquarius. Most years, you`re able to ease in at your own languid pace, because the Sun is making its annual visit to Capricorn and your restful, flowy twelfth house until January 19. This realm rules endings and transitions, and you probably won`t be ready for any hardcore New Year`s resolutions until Aquarius season begins after that.')
pisces = Western.create(sign: 'pisces', element: 'water', quality: 'mutable', planet: 'Jupiter', img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Pisces.svg', description: 'Pisces are very friendly, so they often find themselves in a company of very different people. Pisces are selfless, they are always willing to help others, without hoping to get anything back.', horoscope: "Get set for an adventurous start to 2018! January shows no signs of things slowing down until later in the month for you, Pisces. (And even then…not fully.) With the Sun trotting through Capricorn and your eleventh house of networking until January 19, you're craving community and collaboration as the calendar turns. Cast a wide net! The two risk-taker planets, daring Mars and enthusiastic Jupiter, are both in Scorpio this month, activating your ninth house of travel, widened horizons and growth.")

# Eastern Horoscope

rat = Eastern.create(sign: 'rat',description: 'With strong intuition and quick response, they always easily adapt themselves to a new environment. With rich imaginations and sharp observation, Rats can take advantage of various opportunities well. Rats have strong curiosity, so they tend to try their hands at anything, and they can deal with it skillfully.',lucky_number: "2, 3",lucky_color: "blue, green, gold",img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/rat-2015.jpg')

ox = Eastern.create(sign: 'ox',description: 'Oxes are known for diligence, dependability, strength and determination. Having an honest nature, Oxes have a strong patriotism for their country, have ideals and ambitions for life, and attach importance to family and work.',lucky_number: '1, 4',lucky_color: 'white, yellow, green',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/ox-year.jpg')
tiger = Eastern.create(sign: 'tiger',description: 'People born in the year of the Tiger are brave, competitive, unpredictable, and self-confident. They are very charming and well-liked by others. But sometimes they are likely to be impetuous, irritable, and overindulged.',lucky_number: '1, 3, 4',lucky_color: 'blue, grey, orange, white',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/2015-tiger.jpg')
rabbit = Eastern.create(sign: 'rabbit',description: 'Rabbits tend to be gentle, quiet, elegant, and alert; quick, skillful, kind, and patient; and particularly responsible. However, they might be superficial, stubborn, melancholy, and overly-discreet. Generally speaking, people who belong to the Rabbit zodiac sign have likable characters.',lucky_number: '3, 4, 6',lucky_color: 'red, pink, purple, blue',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/rabbit-2015.jpg')
dragon = Eastern.create(sign: 'dragon',description: 'Gifted with innate courage, tenacity and intelligence, dragons are enthusiastic and confident. They are not afraid of challenges, and willing to take risks.',lucky_number: '1, 6, 7',lucky_color: 'gold, silver, gray, white',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/dragon-2015.jpg')
snake = Eastern.create(sign: 'snake',description: 'Snakes tend to act according to their own judgments, even while remaining the most private and reticent. They are determined to accomplish their goals and hate to fail.',lucky_number: '2, 8, 9',lucky_color: 'black, red, yellow',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/year-snake.jpg')
horse  = Eastern.create(sign: 'horse',description: 'People born in a year of the Horse are extremely animated, active and energetic. Horses love to be in a crowd, and they can usually be seen on such occasions as concerts, theater performances, meetings, sporting events, and parties.',lucky_number: '2, 3, 7',lucky_color: 'yellow, green',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/horse-2015.jpg')
sheep = Eastern.create(sign: 'sheep',description: 'People born in a year of the Goat are generally believed to be gentle mild-mannered, shy, stable, sympathetic, amicable, and brimming with a strong sense of kindheartedness and justice.',lucky_number: '2, 7',lucky_color: 'green, red, purple',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/goat-year.jpg')
monkey = Eastern.create(sign: 'monkey',description: 'People born in a year of the Monkey have magnetic personalities and are witty and intelligent. Personality traits like mischievousness, curiosity, and cleverness, make them very naughty.',lucky_number: '4, 9',lucky_color: 'white, blue, gold',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/year-monkey.jpg')
rooster = Eastern.create(sign: 'rooster',description: 'People born in a year of the Rooster are very observant. Hardworking, resourceful, courageous, and talented, Roosters are very confident in themselves.',lucky_number: '5, 7, 8',lucky_color: 'gold, brown, yellow',img_url: 'https://images.chinahighlights.com/allpicture/2015/04/f9463344d3ed41479d28dcd7.jpg')
dog = Eastern.create(sign: 'dog',description: 'Dogs are loyal and honest, amiable and kind, cautious and prudent. Due to having a strong sense of loyalty and sincerity, Dogs will do everything for the person who they think is most important.',lucky_number: '3, 4, 9',lucky_color: 'red, green, purple',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/dog-2015.jpg')
pig = Eastern.create(sign: 'pig',description: 'General speaking, Pigs are relatively calm when facing trouble. No matter how difficult the problems are Pigs encounter, they can handle things properly and carefully. They have a great sense of responsibility to finish what they are engaged in.',lucky_number: '2, 5, 8',lucky_color: 'yellow, gray, brown, gold',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/pig-2015.jpg')

rat.eastern_partners = [ox, dragon, monkey]
ox.eastern_partners = [rat, monkey, rooster]
rabbit.eastern_partners = [sheep, monkey, dog, pig]
dragon.eastern_partners = [rooster, rat, monkey]
tiger.eastern_partners = [dragon, horse, pig]
snake.eastern_partners = [dragon, rooster]
horse.eastern_partners = [tiger, sheep, rabbit]
sheep.eastern_partners = [rabbit, horse, pig]
monkey.eastern_partners = [ox, rabbit]
rooster.eastern_partners = [ox, snake]
dog.eastern_partners = [rabbit]
pig.eastern_partners = [tiger]
