# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

elli = User.create(full_name: "Elli Shim", birthdate: '12/12/1990')
jon = User.create(full_name: "Jon Wu", birthdate: '23/7/1987')
greg = User.create(full_name: "Greg Driza", birthdate: "22/10/1994")
rochel = User.create(full_name: "Rochel Levi", birthdate: '27/2/1996')
dan = User.create(full_name: "Dan O'Dea", birthdate: '18/6/1979')
brendan = User.create(full_name: "Brendan McIlhenny", birthdate: '2/6/1993')
erica = User.create(full_name: "Erica Li", birthdate: '4/4/1992')
george = User.create(full_name: "Georce Gore", birthdate: '13/6/1993')
josh = User.create(full_name: "Josh Wasserman", birthdate: '24/1/1995')
paul = User.create(full_name: "Paul Kristapovich", birthdate: '9/3/1988')
yuliya = User.create(full_name: "Yuliya Yasenetska", birthdate: '10/9/1992')
priyam = User.create(full_name: "Priyam Sarma", birthdate: '1/1/1989')
chris = User.create(full_name: "Chris Johnson", birthdate: '24/3/1999')
jake = User.create(full_name: "Jake McNaughton", birthdate: '23/4/1988')
seth = User.create(full_name: "Seth Barden", birthdate: '18/10/1986')
joshS = User.create(full_name: "Josh Stillman", birthdate: '9/12/1983')
kat = User.create(full_name: "Katerina Papacostas", birthdate: '22/3/1988')
tashawn = User.create(full_name: "Tashawn Williams", birthdate: '31/3/1990')
erick = User.create(full_name: "Erick Camacho", birthdate: '14/3/1995')
connie = User.create(full_name: "Connie Wang", birthdate: '7/10/1994')
silvia = User.create(full_name: "Silvia Chung", birthdate: '6/10/1994')


# Western Horoscope
aries = Western.create(sign: 'aries', element: 'fire', quality: 'cardinal', planet: 'Mars', img_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Aries.svg', description: 'Aries rules the head and leads with the head, often literally walking head first, leaning forwards for speed and focus. Its representatives are naturally brave and rarely afraid of trial and risk. They possess youthful strength and energy, regardless of their age and quickly perform any given tasks.')
taurus = Western.create(sign: 'taurus', element: 'earth', quality: 'fixed', planet: 'Venus', img_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Taurus.svg', description: 'Practical and well-grounded, Taurus is the sign that harvests the fruits of labor. They feel the need to always be surrounded by love and beauty, turned to the material world, hedonism, and physical pleasures. People born with their Sun in Taurus are sensual and tactile, considering touch and taste the most important of all senses. Stable and conservative, this is one of the most reliable signs of the zodiac, ready to endure and stick to their choices until they reach the point of personal satisfaction.')
gemini = Western.create(sign: 'gemini', element: 'air', quality: 'mutable', planet: 'Mercury', img_url: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Gemini.svg', description: 'Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face. They are sociable, communicative and ready for fun, with a tendency to suddenly get serious, thoughtful and restless. They are fascinated with the world itself, extremely curious, with a constant feeling that there is not enough time to experience everything they want to see.')
cancer = Western.create(sign: 'cancer', element: 'water', quality: 'cardinal', planet: 'Moon', img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Cancer.svg', description: "Deeply intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know. They are very emotional and sensitive, and care deeply about matters of the family and their home. Cancer is sympathetic and attached to people they keep close. Those born with their Sun in Cancer are very loyal and able to empathize with other people's pain and suffering.")
leo = Western.create(sign: 'leo', element: 'fire', quality: 'fixed', planet: 'Sun', img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Leo.svg', description: "People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to. There is a specific strength to a Leo and their 'king of the jungle' status. Leo often has many friends for they are generous and loyal. Self-confident and attractive, this is a Sun sign capable of uniting different groups of people and leading them as one towards a shared cause, and their healthy sense of humor makes collaboration with other people even easier.")
virgo = Western.create(sign: 'virgo', element: 'earth', quality: 'mutable', planet: 'Mercury', img_url: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Virgo.svg', description: 'Virgos are always paying attention to the smallest details and their deep sense of humanity makes them one of the most careful signs of the zodiac. Their methodical approach to life ensures that nothing is left to chance, and although they are often tender, their heart might be closed for the outer world. This is a sign often misunderstood, not because they lack the ability to express, but because they won’t accept their feelings as valid, true, or even relevant when opposed to reason. The symbolism behind the name speaks well of their nature, born with a feeling they are experiencing everything for the first time.')
libra = Western.create(sign: 'libra', element: 'air', quality: 'cardinal', planet: 'Venus', img_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Libra.svg', description: 'People born under the sign of Libra are peaceful, fair, and they hate being alone. Partnership is very important for them, as their mirror and someone giving them the ability to be the mirror themselves. These individuals are fascinated by balance and symmetry, they are in a constant chase for justice and equality, realizing through life that the only thing that should be truly important to themselves in their own inner core of personality.')
scorpio = Western.create(sign: 'scorpio', element: 'water', quality: 'fixed', planet: 'Mars', img_url: 'https://en.wikipedia.org/wiki/Astrological_sign#/media/File:Scorpio.svg', description: 'Scorpio-born are passionate and assertive people. They are determined and decisive, and will research until they find out the truth. Scorpio is a great leader, always aware of the situation and also features prominently in resourcefulness. Scorpio is a Water sign and lives to experience and express emotions. Although emotions are very important for Scorpio, they manifest them differently than other water signs. In any case, you can be sure that the Scorpio will keep your secrets, whatever they may be.')
sagittarius = Western.create(sign: 'sagittarius', element: 'fire', quality: 'mutable', planet: 'Jupiter', img_url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Sagittarius.svg', description: 'Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs. Their open mind and philosophical view motivates them to wander around the world in search of the meaning of life. Sagittarius is extrovert, optimistic and enthusiastic, and likes changes. Sagittarius-born are able to transform their thoughts into concrete actions and they will do anything to achieve their goals.')
capricorn = Western.create(sign: 'capricorn', element: 'earth', quality: 'cardinal', planet: 'Saturn', img_url: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Capricorn.svg', description: 'Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature. These individuals possess an inner state of independence that enables significant progress both in their personal and professional lives. They are masters of self-control and have the ability to lead the way, make solid and realistic plans, and manage many people who work for them at any time. They will learn from their mistakes and get to the top based solely on their experience and expertise.')
aquarius = Western.create(sign: 'aquarius', element: 'air', quality: 'fixed', planet: 'Saturn', img_url: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Aquarius.svg', description: 'Aquarius is an air sign, and as such, uses his mind at every opportunity. If there is no mental stimulation, they are bored and lack a motivation to achieve the best result.')
pisces = Western.create(sign: 'pisces', element: 'water', quality: 'mutable', planet: 'Jupiter', img_url: 'https://upload.wikimedia.org/wikipedia/commons/9/95/Pisces.svg', description: 'Pisces are very friendly, so they often find themselves in a company of very different people. Pisces are selfless, they are always willing to help others, without hoping to get anything back.')

# Eastern Horoscope

rat = Eastern.create(sign: 'rat',description: 'With strong intuition and quick response, they always easily adapt themselves to a new environment. With rich imaginations and sharp observation, Rats can take advantage of various opportunities well. Rats have strong curiosity, so they tend to try their hands at anything, and they can deal with it skillfully.',lucky_number: "2, 3",lucky_color: "blue, green, gold",img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/rat-2015.jpg')

ox = Eastern.create(sign: 'ox',description: 'Oxes are known for diligence, dependability, strength and determination. Having an honest nature, Oxes have a strong patriotism for their country, have ideals and ambitions for life, and attach importance to family and work.',lucky_number: '1, 4',lucky_color: 'white, yellow, green',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/ox-year.jpg')
tiger = Eastern.create(sign: 'tiger',description: 'People born in the year of the Tiger are brave, competitive, unpredictable, and self-confident. They are very charming and well-liked by others. But sometimes they are likely to be impetuous, irritable, and overindulged.',lucky_number: '1, 3, 4',lucky_color: 'blue, grey, orange, white',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/2015-tiger.jpg')
rabbit = Eastern.create(sign: 'rabbit',description: 'Rabbits tend to be gentle, quiet, elegant, and alert; quick, skillful, kind, and patient; and particularly responsible. However, they might be superficial, stubborn, melancholy, and overly-discreet. Generally speaking, people who belong to the Rabbit zodiac sign have likable characters.',lucky_number: '3, 4, 6',lucky_color: 'red, pink, purple, blue',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/rabbit-2015.jpg')
dragon = Eastern.create(sign: 'dragon',description: 'Gifted with innate courage, tenacity and intelligence, dragons are enthusiastic and confident. They are not afraid of challenges, and willing to take risks.',lucky_number: '1, 6, 7',lucky_color: 'gold, silver, gray, white',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/dragon-2015.jpg')
snake = Eastern.create(sign: 'snake',description: 'Snakes tend to act according to their own judgments, even while remaining the most private and reticent. They are determined to accomplish their goals and hate to fail.',lucky_number: '2, 8, 9',lucky_color: 'black, red, yellow',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/year-snake.jpg')
horse  = Eastern.create(sign: 'horse',description: 'People born in a year of the Horse are extremely animated, active and energetic. Horses love to be in a crowd, and they can usually be seen on such occasions as concerts, theater performances, meetings, sporting events, and parties.',lucky_number: '2, 3, 7',lucky_color: 'yellow, green',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/horse-2015.jpg')
sheep = Eastern.create(sign: 'sheep',description: 'People born in a year of the Goat are generally believed to be gentle mild-mannered, shy, stable, sympathetic, amicable, and brimming with a strong sense of kindheartedness and justice.',lucky_number: '2, 7',lucky_color: 'green, red, purple',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/goat-year.jpg')
monkey = Eastern.create(sign: 'monkey',description: 'People born in a year of the Monkey have magnetic personalities and are witty and intelligent. Personality traits like mischievousness, curiosity, and cleverness, make them very naughty.',lucky_number: '4, 9',lucky_color: 'white, blue, gold',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/year-monkey.jpg')
rooster = Eastern.create(sign: 'rooster',description: 'People born in a year of the Rooster are very observant. Hardworking, resourceful, courageous, and talented, Roosters are very confident in themselves.',lucky_number: '5, 7, 8',lucky_color: 'gold, brown, yellow',img_url: 'https://images.chinahighlights.com/allpicture/2015/04/f9463344d3ed41479d28dcd7.jpg')
dog = Eastern.create(sign: 'dog',description: 'Dogs are loyal and honest, amiable and kind, cautious and prudent. Due to having a strong sense of loyalty and sincerity, Dogs will do everything for the person who they think is most important.',lucky_number: '3, 4, 9',lucky_color: 'red, green, purple',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/dog-2015.jpg')
pig = Eastern.create(sign: 'pig',description: 'General speaking, Pigs are relatively calm when facing trouble. No matter how difficult the problems are Pigs encounter, they can handle things properly and carefully. They have a great sense of responsibility to finish what they are engaged in.',lucky_number: '2, 5, 8',lucky_color: 'yellow, gray, brown, gold',img_url: 'https://data.chinahighlights.com/image/travelguide/culture/zodiac/pig-2015.jpg')

rat.eastern_partners = [ox, dragon, monkey]
ox.eastern_partners = [rat, monkey, rooster]
rabbit.eastern_partners = [sheep, monkey, dog, pig]
dragon.eastern_partners = [rooster, rat, monkey]
tiger.eastern_partners = [dragon, horse, pig]
snake.eastern_partners = [dragon, rooster]
horse.eastern_partners = [tiger, sheep, rabbit]
sheep.eastern_partners = [rabbit, horse, pig]
monkey.eastern_partners = [ox, rabbit]
rooster.eastern_partners = [ox, snake]
dog.eastern_partners = [rabbit]
pig.eastern_partners = [tiger]
